/*
 * Copyright 2026 Stephen T. Casper
 * SPDX-License-Identifier: Apache-2.0
 */

import type { StudyRecord } from "./types";

export const mockStudy: StudyRecord = {
  id: "study-road-test",
  title: "Care Transitions Expert Delphi",
  status: "Active",
  methodId: "modified-delphi",
  owner: "Dr. Rivera",
  coordinator: "M. Chen",
  responseRate: 82,
  securityAlerts: [
    "Dataset export requires Data Custodian review.",
    "AI connector is disabled until explicit configuration and disclosure.",
  ],
  consensusRule: {
    type: "percent_agreement",
    threshold: 80,
    agreementMinRating: 7,
    locked: true,
    lockedAt: "2026-04-29T09:00:00Z",
  },
  checklist: [
    {
      id: "purpose",
      label: "Delphi suitability documented",
      detail: "Research question requires structured expert judgment and uncertainty preservation.",
      complete: true,
      risk: "success",
    },
    {
      id: "consent",
      label: "Consent and withdrawal language ready",
      detail: "Consent explains confidentiality to research team and participant ID linkage.",
      complete: true,
      risk: "success",
    },
    {
      id: "feedback",
      label: "Controlled feedback configured",
      detail: "Median, IQR, distribution, and your prior response are enabled.",
      complete: true,
      risk: "success",
    },
    {
      id: "retention",
      label: "Retention schedule needs final review",
      detail: "Security & Privacy Lead must confirm export and retention defaults.",
      complete: false,
      risk: "warning",
    },
  ],
  signoffs: [
    {
      id: "owner-launch",
      label: "Owner launch approval",
      requiredRole: "study_owner",
      status: "Signed",
      signedBy: "Dr. Rivera",
      signedAt: "2026-04-29T09:05:00Z",
    },
    {
      id: "steward-launch",
      label: "Ethics & methods approval",
      requiredRole: "ethics_methods_steward",
      status: "Signed",
      signedBy: "A. Patel",
      signedAt: "2026-04-29T09:11:00Z",
    },
  ],
  rounds: [
    {
      roundNumber: 1,
      label: "Open-ended elicitation",
      mode: "open-ended",
      status: "Closed",
      responseRate: 91,
      attritionRate: 0,
      deadline: "2026-05-03",
    },
    {
      roundNumber: 2,
      label: "Structured rating",
      mode: "rating",
      status: "ReadyForReview",
      responseRate: 82,
      attritionRate: 9,
      deadline: "2026-05-10",
      blocker: "One AI-derived item still needs dual release signoff before publication.",
    },
    {
      roundNumber: 3,
      label: "Terminal rating",
      mode: "rating",
      status: "NotOpen",
      responseRate: 0,
      attritionRate: 0,
      deadline: "2026-05-17",
    },
  ],
  candidates: [
    {
      id: "candidate-1",
      text: "Clinicians may need timely follow up and adequate staffing during transitions.",
      status: "Edited",
      aiSuggestionId: "ai-101",
      requiresHumanRationale: true,
      preservesMinorityView: false,
      provenance: [
        {
          sourceType: "response",
          sourceId: "r1-response-12",
          excerpt: "Clinicians must always receive timely follow up and adequate staffing.",
          roundNumber: 1,
        },
        {
          sourceType: "human_edit",
          sourceId: "edit-44",
          excerpt: "Human review changed directive language to neutral wording.",
          roundNumber: 2,
        },
      ],
    },
    {
      id: "candidate-2",
      text: "Patients benefit when discharge instructions are written in plain language.",
      status: "Accepted",
      aiSuggestionId: "ai-101",
      requiresHumanRationale: false,
      preservesMinorityView: true,
      provenance: [
        {
          sourceType: "response",
          sourceId: "r1-response-18",
          excerpt: "Patients benefit when discharge instructions are written in plain language.",
          roundNumber: 1,
        },
      ],
    },
  ],
  aiSuggestions: [
    {
      id: "ai-101",
      label: "AI Suggestion (Not Final)",
      feature: "inter_round_synthesis",
      status: "Accepted",
      humanDecisionRequired: true,
      ownerSigned: true,
      stewardSigned: false,
      outputHash: "sha256:91b7b1",
    },
    {
      id: "ai-204",
      label: "AI Suggestion (Not Final)",
      feature: "irb_pack",
      status: "None",
      humanDecisionRequired: true,
      ownerSigned: false,
      stewardSigned: false,
      outputHash: "sha256:34ac02",
    },
  ],
  report: {
    id: "report-final",
    title: "Terminal Round Report",
    thresholdUsed: 80,
    attritionRate: 9,
    includesNonConsensus: true,
    limitations: [
      "Consensus indicates agreement among this panel; it does not establish correctness.",
      "The report preserves non-consensus items and methodological limitations.",
      "Only the latest rating per participant is used for each summarized item.",
    ],
    items: [
      {
        id: "item-1",
        text: "Timely follow up and adequate staffing during transitions.",
        consensusClass: "near_consensus",
        median: 8,
        iqr: 2,
        responseCount: 14,
      },
      {
        id: "item-2",
        text: "Plain-language discharge instructions.",
        consensusClass: "consensus",
        median: 9,
        iqr: 1,
        responseCount: 14,
      },
      {
        id: "item-3",
        text: "A single post-discharge call is sufficient for all patients.",
        consensusClass: "non_consensus",
        median: 5,
        iqr: 4,
        responseCount: 14,
      },
    ],
  },
  auditEvents: [
    {
      id: "audit-1",
      timestamp: "2026-04-29T09:00:00Z",
      actorRole: "study_owner",
      action: "study_version.set_consensus_rule",
      object: "study-road-test",
      risk: "locked",
    },
    {
      id: "audit-2",
      timestamp: "2026-04-29T09:11:00Z",
      actorRole: "ethics_methods_steward",
      action: "study_version.signoff",
      object: "version-1",
      risk: "success",
    },
    {
      id: "audit-3",
      timestamp: "2026-04-29T10:30:00Z",
      actorRole: "study_owner",
      action: "ai.suggestion.materialize_items",
      object: "ai-101",
      risk: "warning",
    },
    {
      id: "audit-4",
      timestamp: "2026-04-29T11:20:00Z",
      actorRole: "data_custodian",
      action: "report.export",
      object: "report-final",
      risk: "danger",
    },
  ],
};

export const mockStudies = [mockStudy];
